apiVersion: v1
kind: Service
metadata:
  name: helloworld-node-port
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - port: 8080
      targetPort: helloworld-port
      nodePort: 30800
